// <auto-generated />
using System;
using CoderUL.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoderUL.Migrations
{
    [DbContext(typeof(DBContextElectricityConsumer))]
    [Migration("20210316175412_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("CoderUL.Model.Counter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfAcceptance")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ElectricityConsumerId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("StateVerificationPeriod")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ElectricityConsumerId");

                    b.ToTable("Counter");
                });

            modelBuilder.Entity("CoderUL.Model.ElectricityConsumer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ElectricityConsumers");
                });

            modelBuilder.Entity("CoderUL.Model.HistoryIndications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CounterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Indications")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CounterId");

                    b.ToTable("HistoryIndications");
                });

            modelBuilder.Entity("CoderUL.Model.Counter", b =>
                {
                    b.HasOne("CoderUL.Model.ElectricityConsumer", null)
                        .WithMany("Counters")
                        .HasForeignKey("ElectricityConsumerId");
                });

            modelBuilder.Entity("CoderUL.Model.HistoryIndications", b =>
                {
                    b.HasOne("CoderUL.Model.Counter", null)
                        .WithMany("historyIndications")
                        .HasForeignKey("CounterId");
                });

            modelBuilder.Entity("CoderUL.Model.Counter", b =>
                {
                    b.Navigation("historyIndications");
                });

            modelBuilder.Entity("CoderUL.Model.ElectricityConsumer", b =>
                {
                    b.Navigation("Counters");
                });
#pragma warning restore 612, 618
        }
    }
}
